[package]
name = "intersector"
version = "0.1.0"
authors = ["Patrick Thomas <patrick-thomas@gmx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term-painter = "0.2.4"